site_name: MyMkDocs
nav:
  - Home: index.md
  - About: about.md
  - 技術メモ: diary.md
  - sample: sample.md
  - mkdocs-how-to: mkdocs_howto.md
  - IT:
    - python:
        - django: IT/python/django/tips.md
theme:
    name: material
    language: ja
    features:
        - navigation.tabs
        - navigation.sections
        - navigation.expand
        - navigation.path
    palette:
        - scheme: default
          toggle:
              icon: material/toggle-switch-off-outline
              name: ダークモードに切り替えます。
        - scheme: slate
          primary: blue
          accent: blue
          toggle:
              icon: material/toggle-switch
              name: ライトモードに切り替えます


plugins:
- search
- open-in-new-tab
- git-revision-date-localized
- mkdocstrings
- enumerate-headings

markdown_extensions:
    - markdown.extensions.toc:
        slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}
        permalink: "\ue157"
    - attr_list
    - toc:
        #slugify: !!python/name:src.mytest.slugify
        permalink: "#"
        baselevel: 2
        separator: "_"
    # コードハイライトの設定
    - pymdownx.snippets:
    - codehilite:
        noclasses: true
        pygments_style: colorful
        linenums: false
    # アラート修飾の設定
    - admonition
    # スーパーフェンス機能の設定
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    #注
    - footnotes



